a=input('Digite algo: ')
print('O tipo primitivo desse valor é,',type(a))
print('Só tem espaços ?', a.isspace())
print('É um número ?',a.isnumeric())
print('Só tem letras ?',a.isalpha())
print('É alfanumérico ?',a.isalnum())
print('Está apenas em minúsculas ?',a.islower())
print('Está apenas em maiúsculas ?',a.isupper())
print('Está capitalizado',a.istitle())