nome=input('Digite seu nome completo: ').strip()
n=nome.split()
print('muito bem vindo {}!'.format(n[0]))
print('Seu primeiro nome é {}!'.format(n[0]))
print('Seu último nome é {}!'.format(n[len(n)-1]))
